
#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

if(SB_CONFIG_BOARD_KESTREL_NRF9151_NS)
  if(SB_CONFIG_KESTREL_STATIC_PARTITIONS_FACTORY)
    set(PM_STATIC_YML_FILE ${CMAKE_CURRENT_LIST_DIR}/kestrel_nrf9151_pm_static.yml CACHE INTERNAL "")
  endif()
endif()

if(SB_CONFIG_BOARD_KESTREL_NRF5340_CPUAPP OR SB_CONFIG_BOARD_KESTREL_NRF5340_CPUAPP_NS)
  if(SB_CONFIG_KESTREL_STATIC_PARTITIONS_FACTORY)
    set(PM_STATIC_YML_FILE ${CMAKE_CURRENT_LIST_DIR}/kestrel_nrf5340_pm_static.yml CACHE INTERNAL "")
  endif()
  if(SB_CONFIG_KESTREL_STATIC_PARTITIONS_NRF53_EXTERNAL_FLASH)
    set(PM_STATIC_YML_FILE ${CMAKE_CURRENT_LIST_DIR}/kestrel_nrf5340_pm_static_ext_flash.yml CACHE INTERNAL "")
  endif()
endif()



set(${DEFAULT_IMAGE}_EXTRA_ZEPHYR_MODULES ${CMAKE_CURRENT_LIST_DIR}/spi_bus_share CACHE INTERNAL "")

if(SB_CONFIG_BOOTLOADER_MCUBOOT)
  set(mcuboot_EXTRA_ZEPHYR_MODULES ${CMAKE_CURRENT_LIST_DIR}/spi_bus_share CACHE INTERNAL "")

  set(mcuboot_OVERLAY_CONFIG ${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot.conf)
  set(mcuboot_DTC_OVERLAY_FILE ${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot.overlay)

  if(SB_CONFIG_BOARD_KESTREL_NRF9151_NS)
    list(APPEND mcuboot_DTC_OVERLAY_FILE ${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot_nrf9151.overlay)
    list(APPEND mcuboot_OVERLAY_CONFIG ${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot_nrf9151.conf)
  elseif(SB_CONFIG_BOARD_KESTREL_NRF5340_CPUAPP_NS OR SB_CONFIG_BOARD_KESTREL_NRF5340_CPUAPP)
    list(APPEND mcuboot_DTC_OVERLAY_FILE ${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot_nrf5340.overlay)
    list(APPEND mcuboot_OVERLAY_CONFIG ${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot_nrf5340.conf)
  endif()

  set(mcuboot_OVERLAY_CONFIG ${mcuboot_OVERLAY_CONFIG} CACHE INTERNAL "")
  set(mcuboot_DTC_OVERLAY_FILE ${mcuboot_DTC_OVERLAY_FILE} CACHE INTERNAL "")
endif()